---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1vuddqa0qdc42cvm97euqpjn3m4dxd9fr38k539edgtwa5tep6snqp2k0md
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1vuddqa0qdc42cvm97euqpjn3m4dxd9fr38k539edgtwa5tep6snqp2k0md
