---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfspv
  resources:
    requests:
      storage: 30G
