---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfspv
  resources:
    requests:
      storage: 1G
